blogs/urls.py
from django.urls import path

from . import views

app_name = 'blogs'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:post_id>/', views.detail, name = 'detail'),
    path('<int:post_id>/vote', views.vote, name = 'vote'),
]

src/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('blogs.urls')),
    path('blogs/', include('blogs.urls')),
    path('admin/', admin.site.urls),
]

blogs/models.py
from django.db import models

# Create your models here.

class Author(models.Model):
    name = models.CharField(max_length = 256, verbose_name = 'Name')

    def __str__(self):
        return self.name

class Post(models.Model):
    title = models.CharField(max_length = 256, verbose_name = 'Title')
    body = models.CharField(max_length = 1024, verbose_name = 'Body')
    created_time = models.DateTimeField(verbose_name = "Time created")
    author = models.ForeignKey(Author, on_delete = models.CASCADE)
    vote = models.IntegerField(verbose_name = "Number of votes", default = 0)

    def __str__(self):
        return f"{self.title}: {self.body}"

blogs/views.py
from urllib.request import HTTPPasswordMgrWithPriorAuth
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse

from .models import Post

# Create your views here.

def index(request):
    latest_posts = Post.objects.order_by('-created_time')[:10]
    return render(request, 'blogs/index.html', {'latest_posts': latest_posts})

def detail(request, post_id):
    post = get_object_or_404(Post, pk = post_id)
    return render(request, 'blogs/detail.html', {'post': post})

def vote(request, post_id):
    return HttpResponse("Voted")

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        {% block title %}
        {% endblock title %}
    </head>
    <body>
        <div class = "Navigation">
            <a href = "{% url 'blogs:index' %}">Blogs</a>
        </div>

        <hr>

        {% block content %}
        {% endblock content %}
    </body>
</html>

templates/blogs/detail.html
{% extends "base.html" %}

{% block content %}

    <h1>{{ post.title }}</h1>
    <p>By <b>{{ post.author }}</b>, at {{ post.created_time }}</p>

    <p>Vote: {{ post.vote }}</p>

    <hr>

    <p>{{ post.body }}</p>

    <hr>

    <form action = "{% url 'blogs:vote' post.id %}" method = "post">
    {% csrf_token %}
        <input type = "button" value = "Upvote">
        <input type = "button" value = "Downvote">
        <br>
        <input type = "submit" value = "Submit">
    </form>

{% endblock content %}

templates/blogs/index.html
{% extends "base.html" %}

{% block title %}
    <title>Latest blogs</title>
{% endblock title %}

{% block content %}

{% if latest_posts %}

    <p>Latest posts:</p>
    <ul>
        {% for post in latest_posts %}
        <li>
            <a href = "{% url 'blogs:detail' post.id %}">{{ post.title }}</a>
        </li>
        {% endfor %}
    </ul>

{% else %}

    <p>There are no posts available.</p>

{% endif %}

{% endblock content %}